name: Dynmap-Towny
main: org.dynmap.towny.DynmapTownyPlugin
version: ${project.version}
author: LlmDl
api-version: 1.14
depend: [ dynmap, Towny ]
softdepend: [ TownyChat ]
folia-supported: true
